baseURL = "https://carsonfisher.github.io/"
relativeURLs = true
canonifyURLs = false
languageCode = "en-us"
title = "Yelper"
theme = "simple"
 # Path to site logo file under /static/images
[params]
  # Name of the logo file under /static/images (place your logo here)
  logo = "logo.png"

[menu]
  [[menu.main]]
    name = "Features"
    url = "/features/"
    weight = 1
  [[menu.main]]
    name = "Screenshots"
    url = "#screenshots"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 3
